Remove lms-main-v2 template override
This was removed in edx-platform in edx/edx-platform#24624

This should fix this error:

```
sass.CompileError: b"Error: File to import not found or unreadable: lms/static/sass/lms-main-v2
    Parent style sheet: /edx/var/edxapp/themes/simple-theme/lms/static/sass/lms-main-v2.scss
    on line 1 of ../../../var/edxapp/themes/simple-theme/lms/static/sass/lms-main-v2.scss
    >> @import 'lms/static/sass/lms-main-v2';
       ^
```